name: DevSpaceWeb publish

on:
  push:
     paths:
      - 'DevSpaceWeb/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish
      if: github.event.workflow_run.head_branch == "master"
      run: dotnet publish --no-build --os linux --arch x64 /t:PublishContainer -p ContainerRegistry=ghcr.io
